### ISSUE TITLE
Indicator volume_adi has INF (infinitive) value ?

### ISSUE THREAD

**Issue by thusinh1969** [bukosabino/ta#11]
Hi,

My dataset somehow posed a inf (infinitive) avlue in indicator volume_adi. Any reason why ? I tried stockstats and never had such weird error.

Thanks in advanced.
Steve

**Comment by coire** [comment]
It is best to post the data you're looking at and the code you're running in order to determine what has happened and whether it's expected. 

For this indicator, in the background there are some divisions, so I'm guessing it's related to a division by zero somewhere in the calculation. It might not be avoidable. No additional diagnostics are possible without the example code and source data, though.

**Comment by thusinh1969** [comment]
I have a VNINDEX (Vietnam) from 1/1/2010 to 20 July 2018 with Date Open High Low Close Volume. I checked nothing was zero in the dataset. Please have a look if you have time.

Thank you.
Steve
[VNI.csv.zip](https://github.com/bukosabino/ta/files/2217147/VNI.csv.zip)

**Comment by coire** [comment]
I've taken a quick look at the data and used that same function.

np.isinf(df.volume_adi).any()

seems to return no inf values for this indicator. 

The only thing I can see is that the row for 2010-01-04 will be NaN unless you set fillna=True in the function call. If you're seeing something different, you need to post minimal example code demonstrating the issue.

**Comment by coire** [comment]
Perhaps let’s close this since there is not enough to demonstrate the issue. @bukosabino
