### ISSUE TITLE
RuntimeWarning

### ISSUE THREAD

**Issue by riodda** [bukosabino/ta#152]
Hi, i made a script to fetch data from binance, the pandas dataframe works fine with TA-Lib, on ta it produces this warning:

`C:\ProgramData\Anaconda3\lib\site-packages\ta\trend.py:567: RuntimeWarning: invalid value encountered in double_scalars
  dip[i] = 100 * (self._dip[i]/self._trs[i])
C:\ProgramData\Anaconda3\lib\site-packages\ta\trend.py:571: RuntimeWarning: invalid value encountered in double_scalars
  din[i] = 100 * (self._din[i]/self._trs[i])
`

this is my code (still learning python, please don't lough too loud ! )

`def get_ticker_data(_symbol):
  
    klines = client.get_historical_klines(_symbol, Client.KLINE_INTERVAL_1MINUTE, "1 day ago EST")    
    _data = pd.DataFrame(klines)
    _data=_data.astype(float)
    _data.rename(columns={0:'Open time', 1:'Open',2:'High',3:'Low' ,4:'Close' ,5:'Volume',6:'Close time',7:'Quote asset volume',8:'Number of trades',9:'Taker buy base asset volume',10:'Taker buy quote asset volume',11:'Ignore'}, inplace=True)
    _data.set_index('Open time')
    _data['Open time']=pd.to_datetime(_data['Open time'],unit='ms')
    _data['Close time']=pd.to_datetime(_data['Close time'],unit='ms')
    _data=_data.dropna()
    return _data
`

**Comment by bukosabino** [comment]
Hi @riodda , 

This warning is a well-known problem. I will close this issue because is duplicated: https://github.com/bukosabino/ta/issues/83

At the moment, you can use the library ignoring the warning message. I will fix it as soon as possible!

Just ask here if you need some help with `ta` library or `Python` in general.

Best,
Dario
