### ISSUE TITLE
EMA keeps changing

### ISSUE THREAD

**Issue by palmbook** [bukosabino/ta#20]
Dear Developer,

Let me first express my gratitude for your project. I believe this is one of the best technical indicator library for python.

However, over the past couple of weeks, I have been having trouble with regression test. At first, the library had "ema_fast" and "ema_slow" functions, which were then replaced by a single "ema." This ema function had the default period of 14. However, the default value was removed as of version 2.

This results in code breaking down everytime the library is upgraded. This would make it difficult to use this library for a production code. I would like to suggest that you should not change the function signature outright, but rather show "deprecation warning" for a few versions first. So, people can migrate their codes.

Thank you very much.

**Comment by bukosabino** [comment]
Hi @palmbook , thank you for your advice!

However, for the version 2 had changed the implementation of ema exclusively. So, you can use the "ema_fast" and "ema_slow" functions because the wrapper (API for users -> https://github.com/bukosabino/ta/blob/master/ta/wrapper.py) is not changed.

After, we use this to implement ema:
```python
series.ewm(n).mean()
```

Now, we use a new ema function:
```python
def ema(series, periods):
    sma = series.rolling(window=periods, min_periods=periods).mean()[:periods]
    rest = series[periods:]
    return pd.concat([sma, rest]).ewm(span=periods, adjust=False).mean()
```

This change should be "transparent" for the library users.

Regards.
