### ISSUE TITLE
Why ta Stochastic-Oscillator is differ from trading view that

### ISSUE THREAD

**Issue by HamidMousavi-git** [bukosabino/ta#201]
I did enter the same values in tradingview library and ta for for stochastic, but these two are different. Ta has more noise.
I gave more values ​​to the d_n, but only the slowed was changed and the slow k line does not change.
How I can reduce the noise in slow k that have a smoothed line. (Similar tradingview)

![binance_btc_usdt_1h](https://user-images.githubusercontent.com/63416797/97810708-2616ea80-1c8b-11eb-8a48-0f7adad1277b.png)

**Comment by Sinansi** [comment]
Some technical indicators internally use other technical indicators. For example, after calculating the Stochastic Oscillator, you can use a Simple Moving Average internally to smooth the final output of the Stochastic Oscillator. Some implementations prefer to internally use Exponential Moving Average instead of Simple Moving Average. In such a case, the Stochastic Oscillator will be more responsive but more noisy. For the chart you displayed, I believe they are using different smoothers (filters) internally.

**Comment by HamidMousavi-git** [comment]
Thank you for helping
I used the sma indicator with period 3 on the stochastic oscillator (%D and %K) and the result was exactly the same as Tradingview.

![image](https://user-images.githubusercontent.com/63416797/97815757-a77b7680-1ca5-11eb-91e6-7c2559a69b84.png)

**Comment by Sinansi** [comment]
You are welcome!
