### ISSUE TITLE
Wrong Bollinger Band?!

### ISSUE THREAD

**Issue by Jiraiyah** [bukosabino/ta#55]
Hi
I have the whole 1 hour candle data of bitcoin from bitmex, you can't say they are wrong.
Then i replace nan with epsilon values
Collecting the data from index one forward
using the same code you showed in the read me for bollinger

the bollingers are,... anything but bollinger ! they are more like a spike every now and then between 0 and 1 !!!

http://prntscr.com/nbdmz4

the correct function call should be bollinger_lband for the bollinger bands themselves, maybe you could correct the ream me file. I understand that you are calculating something different for bollinger band indicator method. but showing an image of bollinger in read me, then putting those two function calls as example, will confuse users.

Also, a little file that showed all the available functions with their parameters as a reference would be nice. if you want, i can put near an hour and make that list for you

**Comment by bukosabino** [comment]
Hi @Jiraiyah ,

For Bollinger Bands technical analysis indicator you get 5 columns:
* bollinger_hband
* bollinger_lband
* bollinger_mavg
* bollinger_hband_indicator
* bollinger_lband_indicator

You need to understand the difference between `Bollinger Bands` and `Bollinger Indicators from Bollinger Bands`.

For example:

* bollinger_hband_indicator: 1 if close (price) crosses the upper band from below 0 otherwise.
* bollinger_lband_indicator: 1 if close (price) crosses the lower band from above 0 otherwise

You can check the official documentation for this library: https://technical-analysis-library-in-python.readthedocs.io/en/latest/ta.html#volatility-indicators

**Comment by Jiraiyah** [comment]
I noticed that, just mentioned that anyone who would look at the repo for the first time, chances are that he would look into the read me and give the command example ago to decide if he likes this repo or not, by the way, really just job on the repo.

**Comment by bukosabino** [comment]
You can download any website and check it in your computer.

Bollinger Bands implementation was updated in the last library version (0.4.7)

Check [this issue](https://github.com/bukosabino/ta/issues/74) to get more information
